close all;

d_s = 1.5e-3;
D_s = d_s + 4.75e-3;
N   = 25;
R   = D_s / d_s;
W_c = (4 * R - 1) / (4 * R - 4) + 0.615 / R;

tau_scr = 60e6;
tau_fcr = 320e6;
G_M     = 14.39e9;
G_A     = 18.75e9;
gamma_L = 0.02;
delta_L = gamma_L * pi * N * D_s^2 / d_s;
C1 = 8 * W_c * D_s / (pi * d_s^3);
C2 = d_s / (pi * N * D_s^2);
K = C2 / C1;%d_s^4 / (8 * N * W_c * D_s^3);

A_s = 40.83;
A_f = 44.55;
C_M = 11.51e6;
C_A = 39.55e6;
a_A = pi / (A_f - A_s);

% calculate force and xi_s during pre-stretch
delta = (0 : 5 : 50) * 1e-3;
xi_S_pre = zeros(1, length(delta));
x_pre = zeros(1, length(delta));
for i = 1 : length(delta)
    if i > 1
        if x_pre(i - 1) < tau_scr / C1
            xi_S_pre(i) = 0;
            x_pre(i) = fsolve( ...
            @(F) C1 * F - C2 * G_M * delta(i) + ...
                C2 * delta_L * G_M * (xi_S_pre(i)), ...
            40);
        elseif x_pre(i - 1) < tau_fcr / C1
            x_pre(i) = fsolve( ...
                @(F) C1 * F - C2 * G_M * delta(i) + ...
                    C2 * delta_L * G_M * (1/2 * cos(pi / (tau_scr - tau_fcr) * (F*C1 - tau_fcr)) + 1/2), ...
                40);
            xi_S_pre(i) = 1/2 * cos(pi / (tau_scr - tau_fcr) * (x_pre(i)*C1 - tau_fcr)) + 1/2;
        else
            x_pre(i) = fsolve( ...
            @(F) C1 * F - C2 * G_M * delta(i) + ...
                C2 * delta_L * G_M * (1), ...
            40);
            xi_S_pre(i) = 1;
        end
    end
end

% calculate force of active spring
T = 30 : 0.1 : 60;
x_heat = zeros(length(delta), length(T));
l      = zeros(length(delta), length(T));
xi     = zeros(length(delta), length(T));
for i = 1 : length(delta)
    x_heat(i, 1) = x_pre(i);
    l(i, 1) = delta(i);
    for j = 2 : length(T)
        if T(j) < A_s + x_heat(i, j - 1) * C1 / C_A
            x_heat(i, j) = x_pre(i);
            l(i, j)      = delta(i);
        elseif T(j) < A_f + x_heat(i, j - 1) * C1 / C_A
            % if x_heat(i, j - 1) * C1 < tau_scr
            %     fucn = @(Fl) [ ...
            %         Fl(1) - K * (G_A + (G_M - G_A) * 1/2 * (cos(a_A * (T(j) - A_s - Fl(1)*C1/C_A)) + 1)) * ( ...
            %             Fl(2) - delta_L * ( ...
            %                 xi_S_pre(i) - xi_S_pre(i)/1 * (1 - 1/2 * (cos(a_A * (T(j) - A_s - Fl(1)*C1/C_A)) + 1)) ...
            %             ) ...
            %         );
            %         Fl(1) - K * G_M * ( ...
            %             2 * delta(i) - Fl(2) - delta_L * ( ...
            %                 xi_S_pre(i) ...
            %             ) ...
            %         )
            %     ];
            % elseif x_heat(i, j - 1) * C1 < tau_fcr
            %     fucn = @(Fl) [ ...
            %         Fl(1) - K * (G_A + (G_M - G_A) * 1/2 * (cos(a_A * (T(j) - A_s - Fl(1)*C1/C_A)) + 1)) * ( ...
            %             Fl(2) - delta_L * ( ...
            %                 xi_S_pre(i) - xi_S_pre(i)/1 * (1 - 1/2 * (cos(a_A * (T(j) - A_s - Fl(1)*C1/C_A)) + 1)) ...
            %             ) ...
            %         );
            %         Fl(1) - K * G_M * ( ...
            %             2 * delta(i) - Fl(2) - delta_L * ( ...
            %                 (1 - xi_S_pre(i))/2 * cos(pi / (tau_scr - tau_fcr) * (Fl(1)*C1 - tau_fcr)) + (1 + xi_S_pre(i))/2 ...
            %             ) ...
            %         )
            %     ];
            % else
            %     fucn = @(Fl) [ ...
            %         Fl(1) - K * (G_A + (G_M - G_A) * 1/2 * (cos(a_A * (T(j) - A_s - Fl(1)*C1/C_A)) + 1)) * ( ...
            %             Fl(2) - delta_L * ( ...
            %                 xi_S_pre(i) - xi_S_pre(i)/1 * (1 - 1/2 * (cos(a_A * (T(j) - A_s - Fl(1)*C1/C_A)) + 1)) ...
            %             ) ...
            %         );
            %         Fl(1) - K * G_M * ( ...
            %             2 * delta(i) - Fl(2) - delta_L * ( ...
            %                 1 ...
            %             ) ...
            %         )
            %     ];
            % end

            if x_heat(i, j - 1) * C1 < tau_scr
                fucn = @(Fl) [ ...
                    Fl(1) - K * (G_A + (G_M - G_A) * 1/2 * (cos(a_A * (T(j) - A_s - Fl(1)*C1/C_A)) + 1)) * ( ...
                        Fl(2) - delta_L * ( ...
                            xi_S_pre(i) - xi_S_pre(i)/1 * (1 - 1/2 * (cos(a_A * (T(j) - A_s - Fl(1)*C1/C_A)) + 1)) ...
                        ) ...
                    );
                    Fl(1) - K * G_M * ( ...
                        2 * delta(i) - Fl(2) - delta_L * ( ...
                            xi_S_pre(i) ...
                        ) ...
                    )
                ];
            elseif x_heat(i, j - 1) * C1 < tau_fcr
                fucn = @(Fl) [ ...
                    Fl(1) - K * (G_A + (G_M - G_A) * 1/2 * (cos(a_A * (T(j) - A_s - Fl(1)*C1/C_A)) + 1)) * ( ...
                        Fl(2) - delta_L * ( ...
                            xi_S_pre(i) - xi_S_pre(i)/1 * (1 - 1/2 * (cos(a_A * (T(j) - A_s - Fl(1)*C1/C_A)) + 1)) ...
                        ) ...
                    );
                    Fl(1) - K * G_M * ( ...
                        2 * delta(i) - Fl(2) - delta_L * ( ...
                            1/2 * cos(pi / (tau_scr - tau_fcr) * (Fl(1)*C1 - tau_fcr)) + 1/2 ...
                        ) ...
                    )
                ];
            else
                fucn = @(Fl) [ ...
                    Fl(1) - K * (G_A + (G_M - G_A) * 1/2 * (cos(a_A * (T(j) - A_s - Fl(1)*C1/C_A)) + 1)) * ( ...
                        Fl(2) - delta_L * ( ...
                            xi_S_pre(i) - xi_S_pre(i)/1 * (1 - 1/2 * (cos(a_A * (T(j) - A_s - Fl(1)*C1/C_A)) + 1)) ...
                        ) ...
                    );
                    Fl(1) - K * G_M * ( ...
                        2 * delta(i) - Fl(2) - delta_L * ( ...
                            1 ...
                        ) ...
                    )
                ];
            end

            S = fsolve(fucn, [x_heat(i, j-1); l(i, j-1)]);
            x_heat(i, j) = S(1);
            l(i, j)      = S(2);
            % xi(i, j) = 1/2 * (cos(a_A * (T(j) - A_s - x_heat(i, j)*C1/C_A)) + 1);
        else
            x_heat(i, j) = x_heat(i, j-1);
            l(i, j)      = l(i, j-1);
        end
    end
end

% figure('Name', 'force vs. dis');
% hold on;
% grid on;
% plot(delta, x_pre);
% plot([0, delta(end)], [tau_scr / C1, tau_scr / C1]);
% plot([0, delta(end)], [tau_fcr / C1, tau_fcr / C1]);
% % plot(delta * C2, x_pre * C1);
% % plot([0, delta(end) * C2], [tau_scr, tau_scr]);
% % plot([0, delta(end) * C2], [tau_fcr, tau_fcr]);
% hold off;

% figure('Name', 'stress vs. strain');
% hold on;
% grid on;
% plot(delta * C2, x_pre * C1 * 1e-6);
% plot([0, delta(end) * C2], [tau_scr * 1e-6, tau_scr * 1e-6]);
% plot([0, delta(end) * C2], [tau_fcr * 1e-6, tau_fcr * 1e-6]);
% hold off;

color_map = [ ...
    217   83   25; ...
      0  114  189; ...
    237  177   32; ...
    126   47  142; ...
    119  177   48
];
figure('Name', 'stroke');
hold on;
grid on;
box on;
for i = length(delta) : -1 : 7
    plot(T, (delta(i) - l(i, :)) * 1e3 / 5.2 / pi * 180, '-', 'LineWidth', 1, 'Color', color_map(i - 6, :) / 255);
end
legend('50mm', '45mm', '40mm', '35mm', '30mm', 'Location', 'northwest');
hold off;
xlabel('Temperature ({}^{\circ}C)', 'Fontsize', 8);
ylabel('Stroke (degree)', 'Fontsize', 8);
% xlim([40 60]);
% ylim([0 250]);
% xticks(0.1 : 0.1 : 0.5);
% yticks([-90 -60 -30 0]);
set(gca, 'FontName', 'Times New Roman','Fontsize', 8);

set(gcf, 'Units', 'Inches', 'Position', [0, 0, 3.5, 1.5], 'PaperUnits', 'Inches', 'PaperSize', [3.5, 1.5]);
saveas(gcf, '..\..\paper\v1.0.0\figures\stroke_vs_temperature.pdf');
filename = '..\..\paper\v1.0.0\figures\stroke_vs_temperature.tiff';
% print(gcf, filename, '-dtiffn', '-r600');


% figure('Name', 'force');
% hold on;
% grid on;
% box on;
% for i = 1 : length(delta)
%     % plot(T, x_heat(i, :), '-', 'LineWidth', 1, 'Color', color_map(i - 6, :) / 255);
%     plot(T, x_heat(i, :), '-', 'LineWidth', 1);
% end
% % legend('30mm', '35mm', '40mm', '45mm', '50mm', 'Location', 'northwest');
% hold off;
% xlabel('Temperature ({}^{\circ}C)', 'Fontsize', 8);
% ylabel('Force (N)', 'Fontsize', 8);

